# Generated by Django 3.2.8 on 2022-03-29 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Post title')),
                ('text', models.TextField(verbose_name='Post data')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Post created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Post update')),
                ('is_moderated', models.BooleanField(default=False)),
                ('views', models.BigIntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to=post.models.Post.file_path)),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Link to Post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Post author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Post',
                'db_table': 'posts',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit', models.TextField(max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='comment_created')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_author', to=settings.AUTH_USER_MODEL, verbose_name='comit_author')),
                ('post_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='name_post')),
            ],
            options={
                'verbose_name': 'Commit',
                'db_table': 'Commit',
            },
        ),
    ]
