# Generated by Django 3.2.8 on 2022-03-26 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.category', verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.TextField(max_length=50),
        ),
    ]
